FROM ruby:2.5.1

RUN apt-get update -qq && apt-get install -y apt-transport-https

RUN curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -
RUN echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list
RUN curl -sL https://deb.nodesource.com/setup_10.x | bash

ENV APP /app
RUN apt-get install -y build-essential nodejs npm mysql-client && \
    npm install -g n && \
    n stable && \
    npm install -g yarn && \
    mkdir $APP
